services:
  n8n:
    image: n8nio/n8n:2.0.0-rc.4
    container_name: n8n-app
    expose:
      - "80"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - deploy_net

networks:
  deploy_net:
    external: true

volumes:
  n8n_data:
