services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=n8n.yasasvi.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.yasasvi.dev/
      - N8N_EDITOR_BASE_URL=https://n8n.yasasvi.dev/
      - N8N_PROXY_HOPS=1
      - N8N_SSL_PROXIED=true
      - N8N_SECURE_COOKIE=true
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_METRICS_ENABLED=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=48
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=1000
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - N8N_BLOCK_JS_PYTHON_SOLUTION_ERRORS=false
      - N8N_RUNNERS_MODE=internal
      - N8N_NATIVE_PYTHON_RUNNER=false
    networks:
      - proxy
    ports:
      - "5678:5678"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.5"
          memory: 3G
        reservations:
          cpus: "0.1"
          memory: 200M

networks:
  proxy:
    external: true

volumes:
  n8n_data:
