services:
  focalboard:
    image: mattermost/focalboard
    volumes:
      - focalboard_data:/opt/focalboard/data 
    deploy:
      replicas: 1
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  focalboard_data:
